name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - uses: "ramsey/composer-install@v3"

      # get package json list
      - id: output_data
        run: echo "matrix=$(ls packages | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: Monorepo Split of ${{ matrix.package }}
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'unipay-php'
          repository_name: '${{ matrix.package }}'
          user_name: "bennetgallein"
          user_email: "me@bennetgallein.de"